Miisan: Hello! What would you like to do?
Miisan: nothing to display here but currently needed.
[branch1] short dialog [/branch1] [target:3]
[branch2] long dialog [/branch2] [target:4]

Miisan: You chose short dialog. (end)

Miisan: You chose long dialog.
Miisan: nothing to display here but currently needed.
[branch1] wanna leave ? [/branch1] [target:6]
[branch2] wanna stay ? [/branch2] [target:7]

Miisan:Verywell.
Miisan: You chose to leave. (end)

Miisan: You chose to stay. (end)